app/admin/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField, SelectField
from wtforms.validators import DataRequired

class CennikEdit(FlaskForm):
    "Html forms do edycji cenników"
    nazwa = StringField('Nazwa', validators=[DataRequired()])
    przedzial1 = IntegerField('Przedzial 1', validators=[DataRequired()])
    przedzial2 = IntegerField('Przedzial 2', validators=[DataRequired()])
    cena1 = IntegerField('Cena 1', validators=[DataRequired()])
    cena2 = IntegerField('Cena 2', validators=[DataRequired()])
    submit = SubmitField('Zapisz')

class MagazynEdit(FlaskForm):
    "Html forms do edycji pozycji w magazynie"
    nazwa = StringField('Nazwa', validators=[DataRequired()])
    typ = SelectField('Typ', choices=[('Narty', 'Narty'), ('Deski', 'Deski'), ('Kaski', 'Kaski')])
    ean = StringField('EAN', validators=[DataRequired()])
    rozmiar = StringField('Rozmiar', validators=[DataRequired()])
    price = SelectField('Cennik')
    wartosc = StringField('Wartość', validators=[DataRequired()])
    submit = SubmitField('Zapisz')

app/admin/__init__.py
" Modugł do zarządzania aplikacją, ustawieniami itp.."
from flask import Blueprint

bp = Blueprint('admin', __name__, template_folder='templates')

app/admin/routes.py
from flask import render_template, redirect, url_for, request, flash

from app.admin import bp
from app.admin.forms import CennikEdit, MagazynEdit
from app.db.database import cennik_get, cennik_get_by_id, cennik_update, MagazynUpdate
from app.db.database import cennik_add, MagazynAdd, MagazynGet, MagazynGetById




@bp.route('/cennik')
def cennik():
    pozycje = cennik_get()
    return render_template('cennik.html', pozycje=pozycje)

@bp.route('/cennik/edycja/<int:id>', methods=['POST', 'GET'])
def cennik_edycja(id):
    data = cennik_get_by_id(id)
    form = CennikEdit()

    form.nazwa.data = data['nazwa']
    form.cena1.data = data['price1']
    form.cena2.data = data['price2']
    form.przedzial1.data = data['stage1']
    form.przedzial2.data = data['stage2']

    if form.validate_on_submit():

        cennik_update(
            id,
            request.form['nazwa'],
            request.form['przedzial1'],
            request.form['przedzial2'],
            request.form['cena1'],
            request.form['cena2'],
        )

        flash('Zaktulizowano cennik o nazwie %s'% request.form['nazwa'])
        return redirect(url_for('admin.cennik'))

    return render_template('cennik_edycja.html', form=form, site_name="Edycja cennika")

@bp.route('/cennik/dodaj', methods=['POST','GET'])
def cennik_dodaj():
    form = CennikEdit()

    if form.validate_on_submit():

        cennik_add(
            request.form['nazwa'],
            request.form['przedzial1'],
            request.form['przedzial2'],
            request.form['cena1'],
            request.form['cena2'],
        )

        flash('Dodano pozycje cennika o nazwie %s'% request.form['nazwa'])
        return redirect(url_for('admin.cennik'))

    return render_template('cennik_edycja.html', form=form, site_name="Dodanie pozycji cennika")

@bp.route('/magazyn/')
def magazyn():
    pozycje = MagazynGet()

    return render_template('magazyn.html', pozycje=pozycje)

@bp.route('/magazyn/dodaj', methods=['POST', 'GET'])
def magazyn_dodaj():
    cennik = cennik_get()
    form = MagazynEdit()

    cennik_choices = [(i['cennik_id'], i['nazwa']) for i in cennik]

    form.price.choices = cennik_choices

    if form.validate_on_submit():
        MagazynAdd(
            request.form['nazwa'],
            request.form['typ'],
            request.form['ean'],
            request.form['rozmiar'],
            request.form['price'],
            request.form['wartosc']
        )

        flash('Dodano pozycje do magazynu o nazwie %s'% request.form['nazwa'])
        return redirect(url_for('admin.magazyn'))


    return render_template('magazyn_form.html', form=form)

@bp.route('/magazyn/edytuj/<item_id>', methods=['POST', 'GET'])
def magazyn_edytuj(item_id):
    cennik = cennik_get()
    form = MagazynEdit()
    data = MagazynGetById(item_id)

    cennik_choices = [(i['cennik_id'], i['nazwa']) for i in cennik]
    form.price.choices = cennik_choices

    form.price.default = data['price']
    form.typ.default = data['typ']
    form.process()

    form.nazwa.data = data['nazwa']
    form.ean.data = data['ean']
    form.rozmiar.data = data['rozmiar']
    form.wartosc.data = data['wartosc']

    if request.method == 'POST':
        MagazynUpdate(
            item_id,
            request.form['nazwa'],
            request.form['typ'],
            request.form['ean'],
            request.form['rozmiar'],
            request.form['price'],
            request.form['wartosc']
        )
        flash('Zapisano zmiany w pozycji: %s' % request.form['nazwa'])
        return redirect(url_for('admin.magazyn'))

    return render_template('magazyn_form.html', form=form)

app/admin/templates/cennik.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">Cennik</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
        <a href="{{ url_for('admin.cennik_dodaj') }} " class="btn btn-sm btn-outline-secondary">Dodaj nową pozycje</a>
      </div>
    </div>
  </div>

<div class="row">
{% for poz in pozycje %}
    <div class="col-lg-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{ poz.nazwa }}</h5>
            <table class="table">
                <tbody>
                    <tr>
                      <th>{{ poz.stage1 }}h</th>
                      <td>{{ poz.price1 }}zł</td>
                    </tr>
                    <tr>
                      <th>Więcej niż {{ poz.stage2 }}h</th>
                      <td>{{ poz.price2 }}zł</td>
                    </tr>

                  </tbody>
            </table>
            <a href="{{ url_for('admin.cennik_edycja', id=poz.cennik_id)}}" class="btn btn-primary btn-sm">Edytuj</a>
          </div>
        </div>
    </div>
{% endfor %}
</div>


{% endblock %}

app/admin/templates/cennik_edycja.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">{{ site_name }}</h1>
  </div>

<form method="POST">
    {{ form.csrf_token }}
    <div class="form-row">
        <div class="form-group col-4">
            {{ form.nazwa.label }}
            {{ form.nazwa(class_="form-control") }}
            {% for error in form.nazwa.errors %}
                <small class="form-text text-danger">
                    {{ error }}
                </small>
            {% endfor %}
        </div>
        <div class="form-group col-4">
            {{ form.przedzial1.label }}
            {{ form.przedzial1(class_="form-control") }}
            {% for error in form.przedzial1.errors %}
                <small class="form-text text-danger">
                    {{ error }}
                </small>
            {% endfor %}
        </div>
        <div class="form-group col-4">
            {{ form.cena1.label }}
            {{ form.cena1(class_="form-control") }}
            {% for error in form.cena1.errors %}
                <small class="form-text text-danger">
                    {{ error }}
                </small>
            {% endfor %}
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-4">
        </div>
        <div class="form-group col-4">
            {{ form.przedzial2.label }}
            {{ form.przedzial2(class_="form-control") }}
            {% for error in form.przedzial2.errors %}
                <small class="form-text text-danger">
                    {{ error }}
                </small>
            {% endfor %}
        </div>
        <div class="form-group col-4">
            {{ form.cena2.label }}
            {{ form.cena2(class_="form-control") }}
            {% for error in form.cena2.errors %}
                <small class="form-text text-danger">
                    {{ error }}
                </small>
            {% endfor %}
        </div>
    </div>

    {{ form.submit(class_="btn btn-primary btn-sm") }}
    <a href="{{ url_for('admin.cennik')}}" type="button" class="btn btn-secondary btn-sm">Wróć</a>
</form>

<div style="margin-top: 30px;" class="row">
    <h4>Zasady przypisywania</h4>
</div>
<div class="row">
    <p>Przedział <b>przedzial1</b> to ilość godzin za które klient zapłaci <b>Cena 1</b> <br>
    Czyli gdy <b>przedział1</b> jest ustawione na 1 a <b>cena 1</b> na 10 to za każdą godzinę wypożyczenia jeżeli nie
    trwa dłużej niż <b>przedział 2</b> poprostu <b>cene 1</b> razy ilość godzin</p>
</div>
<div class="row">
    <p>Przedział <b>przedział2</b> to ilość godzin po których powyżej będzie kasowana cena <b>cena 2</b>.
        W tym przypadku jeżeli ktoś bierzę sprzęt na dwa dni, liczona jest dwa razy <b>Cena 2</b> z przedziału <b>Przedział 2</b></p>
    
</div>


{% endblock %}

app/admin/templates/magazyn.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">Magazyn</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
        <a href="{{ url_for('admin.magazyn_dodaj') }} " class="btn btn-sm btn-outline-secondary">Dodaj nową pozycje magazynu</a>
      </div>
    </div>
  </div>

    <table id="ItemTable" class="table table-sm">
      <thead>
        <tr>
          <th scope="col">Nazwa</th>
          <th scope="col">Typ</th>
          <th scope="col">EAN</th>
          <th scope="col">Nazwa cennika</th>
          <th scope="col">Rozmiar</th>
          <th scope="col">Opcje</th>
        </tr>
      </thead>
      <tbody>
        {% for poz in pozycje %}
        <tr>
          <td>{{ poz.nazwa }}</td>
          <td>{{ poz.typ }}</td>
          <td>{{ poz.ean }}</td>
          <td><a href="{{ url_for('admin.cennik_edycja', id=poz.cennik_id) }}">{{ poz.cennik_nazwa }}</a></td>
          <td>{{ poz.rozmiar }}</td>
          <td>
            <a href="{{ url_for('admin.magazyn_edytuj', item_id=poz.item_id)}}" type="button" class="btn btn-primary btn-sm">Edytuj</a>
            <a type="button" class="btn btn-danger btn-sm">Usuń</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

{% endblock %}

{% block scripts %}
<script>
// Basic example
$(document).ready(function () {
    $('#ItemTable').DataTable({
        "pageLength": 100
    });
});
</script>
{% endblock %}

app/admin/templates/magazyn_form.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">Dodawanie pozycji magazynu</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
    </div>
  </div>

<form method="POST">
    {{ form.csrf_token }}
    <div class="form-row">
        <div class="form-group col-4">
            {{ form.nazwa.label }}
            {{ form.nazwa(class_="form-control") }}
            {% for error in form.nazwa.errors %}
                <small class="form-text text-danger">
                    {{ error }}
                </small>
            {% endfor %}
        </div>
        <div class="form-group col-4">
            {{ form.typ.label }}
            {{ form.typ(class_="form-control") }}
            {% for error in form.typ.errors %}
                <small class="form-text text-danger">
                    {{ error }}
                </small>
            {% endfor %}
        </div>
        <div class="form-group col-4">
            {{ form.ean.label }}
            {{ form.ean(class_="form-control") }}
            {% for error in form.ean.errors %}
                <small class="form-text text-danger">
                    {{ error }}
                </small>
            {% endfor %}
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-4">
            {{ form.rozmiar.label }}
            {{ form.rozmiar(class_="form-control") }}
            {% for error in form.rozmiar.errors %}
                <small class="form-text text-danger">
                    {{ error }}
                </small>
            {% endfor %}
        </div>
        <div class="form-group col-4">
            {{ form.wartosc.label }}
            {{ form.wartosc(class_="form-control") }}
            {% for error in form.wartosc.errors %}
                <small class="form-text text-danger">
                    {{ error }}
                </small>
            {% endfor %}
        </div>
        <div class="form-group col-4">
            {{ form.price.label }}
            {{ form.price(class_="form-control") }}
            {% for error in form.price.errors %}
                <small class="form-text text-danger">
                    {{ error }}
                </small>
            {% endfor %}
        </div>
    </div>

    {{ form.submit(class_="btn btn-primary btn-sm") }}
    <a href="{{ url_for('admin.magazyn')}}" type="button" class="btn btn-secondary btn-sm">Wróć</a>
</form>


{% endblock %}